# Generated by Django 5.2 on 2025-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('admin', 'Admin User')], default='regular', max_length=20),
        ),
    ]
